### ISSUE TITLE
Add tests for JobFactory and JobGenerator

### ISSUE THREAD

**Issue by chowder** [chowder/DroNeS-Servers#4]
- [x] JobFactory
- [x] JobGenerator
- [x] JobScheduler

**Comment by 4katie** [comment]
John and I (mostly John) wrote basic tests for JobGenerator and JobScheduler (https://github.com/johnahn92/DroNeS-Servers/tree/master/tests); will now work on writing schema for pathfinder

**Comment by chowder** [comment]
Done now
